import pandas as pd
import matplotlib.pyplot as plt

File = open("SalesData.csv", 'r')
df = pd.read_csv(File)
plt.subplot(2,1,1)
daylist = df['Day'].tolist()
productA_SalesData = df['Product A'].tolist()
productB_SalesData = df['Product B'].tolist()
productC_SalesData = df['Product C'].tolist()
plt.scatter(daylist, productA_SalesData, label ='Product A')
plt.scatter(daylist, productB_SalesData, label ='Product B')
plt.scatter(daylist, productC_SalesData, label ='Product C')
plt.xlabel(' ')
plt.ylabel(' ')
plt.legend(loc='upper right')
plt.title(' Scatter Plot:')

File1 = open("SalesData.csv", 'r')
df1 = pd.read_csv(File1)
plt.subplot(2,1,2)
daylist1 = df1['Day'].tolist()
productA_SalesData = df1['Product A'].tolist()
productB_SalesData = df1['Product B'].tolist()
productC_SalesData = df1['Product C'].tolist()
plt.plot(daylist1, productA_SalesData, label ='Product A')
plt.plot(daylist1, productB_SalesData, label ='Product B')
plt.plot(daylist1, productC_SalesData, label ='Product C')
plt.xlabel(' ')
plt.ylabel(' ')
plt.legend(loc='upper right')
plt.title(' Line Plot:')
plt.show()
File.close()
